CREATE TABLE eemrt.contract (
  contract_number VARCHAR2(200 BYTE) NOT NULL,
  contract_start_date DATE,
  contract_end_date DATE,
  contract_ceiling_value NUMBER(18,2),
  contract_ceiling_hours NUMBER(8),
  vendor VARCHAR2(200 BYTE),
  subcontract_vendor VARCHAR2(200 BYTE),
  routing_symbol VARCHAR2(100 BYTE),
  contract_category VARCHAR2(100 BYTE) DEFAULT 'NA in PRISM',
  buyer VARCHAR2(500 BYTE),
  co_name VARCHAR2(200 BYTE),
  cor_name VARCHAR2(200 BYTE),
  "ORGANIZATION" VARCHAR2(200 BYTE),
  "PROGRAM" VARCHAR2(200 BYTE),
  created_by VARCHAR2(50 BYTE) DEFAULT 'SYS',
  created_on TIMESTAMP DEFAULT SYSDATE,
  last_modified_by VARCHAR2(50 BYTE),
  last_modified_on TIMESTAMP,
  do_num VARCHAR2(100 BYTE) DEFAULT 9999,
  contract_type VARCHAR2(500 BYTE),
  small_business VARCHAR2(1 BYTE) DEFAULT 'N',
  small_business_desig VARCHAR2(50 BYTE),
  award_date VARCHAR2(20 BYTE),
  status VARCHAR2(10 BYTE),
  contract_task_type VARCHAR2(1000 BYTE),
  cs_username VARCHAR2(2000 BYTE),
  pm_username VARCHAR2(2000 BYTE),
  PRIMARY KEY (contract_number)
);