CREATE TABLE eemrt.delphi_inv_sur (
  extract_date DATE,
  po_number VARCHAR2(50 BYTE),
  po_rev NUMBER,
  po_type VARCHAR2(30 BYTE),
  vendor_name VARCHAR2(150 BYTE),
  line_item NUMBER,
  line_number NUMBER,
  line_type VARCHAR2(50 BYTE),
  item_desc VARCHAR2(1000 BYTE),
  release_number VARCHAR2(50 BYTE),
  rel_rev_num NUMBER,
  shipment_num NUMBER,
  quantity_ordered NUMBER,
  quantity_cancelled NUMBER,
  net_qty_ordered NUMBER,
  uom VARCHAR2(50 BYTE),
  unit_price NUMBER,
  distribution_num NUMBER,
  charge_account VARCHAR2(150 BYTE),
  project_number VARCHAR2(30 BYTE),
  task_number VARCHAR2(30 BYTE),
  invoice_num VARCHAR2(30 BYTE),
  invoice_date DATE,
  inv_dist_line NUMBER,
  matching_type VARCHAR2(30 BYTE),
  "ACCOUNT" VARCHAR2(15 BYTE),
  invoice_amount NUMBER,
  kitt_inv_amount NUMBER,
  payment_status_flag CHAR,
  recon_flag CHAR
);