CREATE TABLE eemrt.delphi_contract_detail (
  contract_number VARCHAR2(100 BYTE) NOT NULL,
  lsd VARCHAR2(122 BYTE) NOT NULL,
  accounting_code VARCHAR2(1000 BYTE) NOT NULL,
  quantity_ordered NUMBER,
  quantity_cancelled NUMBER,
  quantity_received NUMBER,
  quantity_billed NUMBER,
  obligated_balance NUMBER,
  balance_amount NUMBER,
  last_modified_by VARCHAR2(200 BYTE),
  last_modified_on TIMESTAMP,
  created_by VARCHAR2(200 BYTE),
  created_on TIMESTAMP,
  release_num VARCHAR2(150 BYTE),
  line_item VARCHAR2(150 BYTE),
  matching_type VARCHAR2(150 BYTE),
  project_number VARCHAR2(150 BYTE),
  task_number VARCHAR2(150 BYTE),
  charge_account VARCHAR2(300 BYTE),
  multiplier VARCHAR2(150 BYTE),
  fund VARCHAR2(150 BYTE),
  budyear VARCHAR2(150 BYTE),
  bpac VARCHAR2(150 BYTE),
  orgcode VARCHAR2(150 BYTE),
  object_class VARCHAR2(150 BYTE),
  "ACCOUNT" VARCHAR2(150 BYTE),
  line_num NUMBER,
  shipment_number NUMBER,
  distribution_num NUMBER,
  stage_date DATE,
  fiscal_year VARCHAR2(4 BYTE),
  fund_type VARCHAR2(30 BYTE),
  obligation_expiration_date DATE,
  expenditure_expiration_date DATE,
  CONSTRAINT delphi_contract_detail_uk1 UNIQUE (contract_number,lsd,accounting_code)
);