CREATE TABLE eemrt.test_delphi_contract_stage (
  stage_date DATE,
  po_number VARCHAR2(150 BYTE),
  vendor_name VARCHAR2(150 BYTE),
  vendor_site_code VARCHAR2(150 BYTE),
  release_num VARCHAR2(150 BYTE),
  line_item VARCHAR2(150 BYTE),
  matching_type VARCHAR2(150 BYTE),
  quantity_ordered NUMBER,
  quantity_billed NUMBER,
  quantity_received NUMBER,
  quantity_cancelled NUMBER,
  obligated_balance NUMBER,
  project_number VARCHAR2(150 BYTE),
  task_number VARCHAR2(150 BYTE),
  charge_account VARCHAR2(300 BYTE),
  multiplier VARCHAR2(150 BYTE),
  fund VARCHAR2(150 BYTE),
  budyear VARCHAR2(150 BYTE),
  bpac VARCHAR2(150 BYTE),
  orgcode VARCHAR2(150 BYTE),
  object_class VARCHAR2(150 BYTE),
  "ACCOUNT" VARCHAR2(150 BYTE),
  line_num NUMBER,
  shipment_number NUMBER,
  distribution_num NUMBER,
  net_qty_ordered NUMBER
);