CREATE OR REPLACE PACKAGE eemrt.PKG_PROGRAMS AS 
  PROCEDURE SP_GET_PROGRAM_LOCATIONS(
      p_UserId          VARCHAR2,
      p_PROGRAM         VARCHAR2,
      PROGRAMLOCATIONS_CURSOR OUT SYS_REFCURSOR) ;
  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

PROCEDURE SP_GET_PROGRAM_CLIN_TYPES(
      p_UserId          VARCHAR2,
      p_PROGRAM         VARCHAR2,
      PROGRAMCLINTYPES_CURSOR OUT SYS_REFCURSOR) ;

PROCEDURE SP_GET_PROGRAM_TASKORDER_TOTAL(
      p_UserId          VARCHAR2,
      p_PROGRAM         VARCHAR2,
      PROGRAMTASKORDERTOTAL_CURSOR OUT SYS_REFCURSOR) ;
 
 
PROCEDURE SP_GET_PROG_TO_TOTAL_CONTRACT(
      p_UserId          VARCHAR2,
      p_Contract         VARCHAR2,
      PROGRAMTASKORDERTOTAL_CURSOR OUT SYS_REFCURSOR) ;
 
 PROCEDURE SP_GET_PROGRAM_COLOR_OF_MONEY(
      p_UserId          VARCHAR2,
      p_PROGRAM         VARCHAR2,
      PROGRAMCOLORMONEY_CURSOR OUT SYS_REFCURSOR) ;
      
  PROCEDURE SP_ADD_INVOICE_HEADER(
      p_UserId          MITRE_INVOICE_HDR.MIH_CREATED_BY%TYPE,
      p_InvoiceNumber   MITRE_INVOICE_HDR.MIH_INVOICE_NUMBER%TYPE,
      p_PeriodStartDate MITRE_INVOICE_HDR.MIH_INVOICE_START_DATE%TYPE,
      p_PeriodEndDate   MITRE_INVOICE_HDR.MIH_INVOICE_END_DATE%TYPE,
      p_InvoiceDate     MITRE_INVOICE_HDR.MIH_INVOICE_RECEIVED_DATE%TYPE,
      p_InvoiceAmount   MITRE_INVOICE_HDR.MIH_INVOICE_AMOUNT%TYPE,
      p_ContractNumber  MITRE_INVOICE_HDR.MIH_CONTRACT_NUMBER%TYPE,
      p_PStatus         OUT VARCHAR2
  );
END PKG_PROGRAMS;
/