CREATE OR REPLACE PACKAGE eemrt.pkg_work_orders
IS
  /*
  Procedure : pkg_work_orders
  Author: Sridhar Kommana
  Date Created : 11/14/2014
  Purpose:  Insert Update Delete Work Order records for eCert
  Update history:
  */
type t_clin_id
IS
  TABLE OF WORK_ORDERS_CLINS.CLIN_ID%type INDEX BY pls_integer;
type t_sub_clin_id
IS
  TABLE OF WORK_ORDERS_CLINS.SUB_CLIN_ID%type INDEX BY pls_integer;

  -- Insert_work_orders  
  PROCEDURE insert_work_orders(
      p_WORK_ORDER_NUMBER        IN work_orders.WORK_ORDER_NUMBER%TYPE DEFAULT NULL,
      p_WORK_ORDER_TITLE         IN work_orders.WORK_ORDER_TITLE%TYPE DEFAULT NULL,
      p_START_DATE               IN work_orders.START_DATE%TYPE DEFAULT NULL,
      p_END_DATE                 IN work_orders.END_DATE%TYPE DEFAULT NULL,
      p_DESCRIPTION              IN work_orders.DESCRIPTION%TYPE DEFAULT NULL,
      p_ORGANIZATION             IN work_orders.ORGANIZATION%TYPE DEFAULT NULL,
      p_FAA_POC                  IN work_orders.FAA_POC%TYPE DEFAULT NULL,
      p_PERIOD_OF_PERFORMANCE_ID IN work_orders.PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_Status                   IN work_orders.Status%TYPE DEFAULT NULL,
      p_WO_FEE                   IN work_orders.WO_FEE%TYPE DEFAULT 0,
      p_Sub_Task                 IN work_orders.sub_task%TYPE DEFAULT NULL,
      p_CLINS                    IN VARCHAR2 DEFAULT NULL,
      p_SUB_CLINS                IN VARCHAR2 DEFAULT NULL,
      p_CLIN_HOURS               IN VARCHAR2 DEFAULT NULL, ---Added by Sridhar on 02062015
      p_CLIN_AMOUNT              IN VARCHAR2 DEFAULT NULL, ---Added by Sridhar on 02062015
      p_CREATED_BY               IN work_orders.CREATED_BY%TYPE DEFAULT NULL,
      p_ID OUT work_orders.WORK_ORDERS_ID%TYPE,
      p_PStatus OUT VARCHAR2 );
  -- Insert_work_orders_clin
  PROCEDURE insert_WORK_ORDERS_CLINS(
      p_WORK_ORDERS_ID           IN WORK_ORDERS_CLINS.FK_WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_PERIOD_OF_PERFORMANCE_ID IN WORK_ORDERS_CLINS.FK_PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_CLIN_ID                  IN WORK_ORDERS_CLINS.CLIN_ID%TYPE DEFAULT NULL,
      p_SUB_CLIN_ID              IN WORK_ORDERS_CLINS.SUB_CLIN_ID%TYPE DEFAULT NULL,
      p_CLIN_HOURS               IN WORK_ORDERS_CLINS.CLIN_HOURS%TYPE DEFAULT NULL,
      p_CLIN_AMOUNT              IN WORK_ORDERS_CLINS.CLIN_AMOUNT%TYPE DEFAULT NULL,
      P_WO_CLIN_TYPE             IN WORK_ORDERS_CLINS.WO_CLIN_TYPE%TYPE DEFAULT NULL,
      P_WO_Rate                  IN WORK_ORDERS_CLINS.WO_Rate%TYPE DEFAULT NULL,
      p_CREATED_BY               IN WORK_ORDERS_CLINS.CREATED_BY%TYPE DEFAULT NULL,
      p_ID OUT WORK_ORDERS_CLINS.WOC_ID%TYPE,
      p_PStatus OUT VARCHAR2 );
  PROCEDURE insert_WO_CLINS_SESSION(
      p_Sub_Tasks_ID             IN WORK_ORDERS_CLINS_SESSION.SUB_TASKS_ID%TYPE DEFAULT NULL,
      p_WORK_ORDERS_ID           IN WORK_ORDERS_CLINS_SESSION.FK_WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_PERIOD_OF_PERFORMANCE_ID IN WORK_ORDERS_CLINS_SESSION.FK_PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_CLIN_ID                  IN WORK_ORDERS_CLINS_SESSION.CLIN_ID%TYPE DEFAULT NULL,
      p_SUB_CLIN_ID              IN WORK_ORDERS_CLINS_SESSION.SUB_CLIN_ID%TYPE DEFAULT NULL,
      p_CLIN_HOURS               IN WORK_ORDERS_CLINS_SESSION.CLIN_HOURS%TYPE DEFAULT NULL,
      p_CLIN_AMOUNT              IN WORK_ORDERS_CLINS_SESSION.CLIN_AMOUNT%TYPE DEFAULT NULL,
      P_WO_CLIN_TYPE             IN WORK_ORDERS_CLINS.WO_CLIN_TYPE%TYPE DEFAULT NULL,
      P_WO_Rate                  IN WORK_ORDERS_CLINS.WO_Rate%TYPE DEFAULT NULL,
      p_CREATED_BY               IN WORK_ORDERS_CLINS_SESSION.CREATED_BY%TYPE DEFAULT NULL,
      p_ID OUT WORK_ORDERS_CLINS_SESSION.WOC_ID%TYPE,
      p_PStatus OUT VARCHAR2 ) ;
  PROCEDURE Move_WO_CLINS_SESSION(
      p_WORK_ORDERS_ID           IN WORK_ORDERS_CLINS_SESSION.FK_WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_PERIOD_OF_PERFORMANCE_ID IN WORK_ORDERS_CLINS_SESSION.FK_PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_CREATED_BY               IN WORK_ORDERS_CLINS_SESSION.CREATED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2 ) ;
  PROCEDURE Delete_WO_CLINS_SESSION(
      p_CREATED_BY IN WORK_ORDERS_CLINS_SESSION.CREATED_BY%TYPE ,
      p_PStatus OUT VARCHAR2 ) ;
  PROCEDURE insert_woc_clinS( ---Inserting only Clin and SubClin
      p_FK_WORK_ORDERS_ID        IN work_orders_clins.FK_WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_PERIOD_OF_PERFORMANCE_ID IN work_orders.PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_CLINS                    IN VARCHAR2 DEFAULT NULL,
      p_SUB_CLINS                IN VARCHAR2 DEFAULT NULL,
      p_CLIN_HOURS               IN VARCHAR2 DEFAULT NULL, ---Added by Sridhar on 02062015
      p_CLIN_AMOUNT              IN VARCHAR2 DEFAULT NULL, ---Added by Sridhar on 02062015
      p_CREATED_BY               IN work_orders.CREATED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2 ) ;
  -- Update_work_order
  PROCEDURE update_work_orders(
      p_work_orders_ID    IN work_orders.work_orders_ID%type ,
      p_WORK_ORDER_NUMBER IN work_orders.WORK_ORDER_NUMBER%TYPE DEFAULT NULL,
      p_WORK_ORDER_TITLE  IN work_orders.WORK_ORDER_TITLE%TYPE DEFAULT NULL,
      p_START_DATE        IN work_orders.START_DATE%TYPE DEFAULT NULL,
      p_END_DATE          IN work_orders.END_DATE%TYPE DEFAULT NULL,
      p_DESCRIPTION       IN work_orders.DESCRIPTION%TYPE DEFAULT NULL,
      p_ORGANIZATION      IN work_orders.ORGANIZATION%TYPE DEFAULT NULL,
      p_FAA_POC           IN work_orders.FAA_POC%TYPE DEFAULT NULL,
      p_Status            IN work_orders.Status%TYPE DEFAULT NULL,
      p_WO_FEE            IN work_orders.WO_FEE%TYPE DEFAULT 0,
      p_Sub_Task          IN work_orders.sub_task%TYPE DEFAULT NULL,
      p_LAST_MODIFIED_BY  IN work_orders.LAST_MODIFIED_BY%type DEFAULT NULL ,
      p_PStatus OUT VARCHAR2 );
  -- Update_work_order_clin
  PROCEDURE update_WORK_ORDERS_CLINS(
      p_WOC_ID           IN WORK_ORDERS_CLINS.WOC_ID%TYPE,
      p_CLIN_HOURS       IN WORK_ORDERS_CLINS.CLIN_HOURS%TYPE DEFAULT NULL,
      p_CLIN_AMOUNT      IN WORK_ORDERS_CLINS.CLIN_AMOUNT%TYPE DEFAULT NULL,
      p_LAST_MODIFIED_BY IN WORK_ORDERS_CLINS.LAST_MODIFIED_BY%type DEFAULT NULL ,
      p_PStatus OUT VARCHAR2);
  -- Update_work_order_clin
  PROCEDURE update_clin_amounts(
      p_WOC_ID           IN VARCHAR2 DEFAULT NULL,
      p_CLIN_HOURS       IN VARCHAR2 DEFAULT NULL,
      p_CLIN_AMOUNT      IN VARCHAR2 DEFAULT NULL,
      p_LAST_MODIFIED_BY IN WORK_ORDERS_CLINS.LAST_MODIFIED_BY%type DEFAULT 'SYS' ,
      p_PStatus OUT VARCHAR2);
  PROCEDURE update_clin_id_amounts(
      p_WOC_ID           IN VARCHAR2 DEFAULT NULL,
      p_CLINS            IN VARCHAR2 DEFAULT NULL, ---comma seperated clinid
      p_SUB_CLINS        IN VARCHAR2 DEFAULT NULL,
      p_CLIN_HOURS       IN VARCHAR2 DEFAULT NULL,
      p_CLIN_AMOUNT      IN VARCHAR2 DEFAULT NULL,
      p_LAST_MODIFIED_BY IN WORK_ORDERS_CLINS.LAST_MODIFIED_BY%type DEFAULT 'SYS' ,
      p_PStatus OUT VARCHAR2);
  -- Delete_work_orders
  PROCEDURE delete_work_orders(
      p_work_orders_ID IN work_orders.work_orders_ID%type,
      P_LAST_MODIFIED_BY         IN work_orders.LAST_MODIFIED_BY%TYPE ,  
      p_PStatus OUT VARCHAR2 );
  -- Delete_work_orders_clin
  PROCEDURE delete_WORK_ORDERS_CLINS(
      p_WOC_ID IN WORK_ORDERS_CLINS.WOC_ID%TYPE,
      p_PStatus OUT VARCHAR2 );
  PROCEDURE UPDATE_WO_LABOR_CATEGORY(
      P_WO_LABOR_CATEGORY_ID  IN WO_LABOR_CATEGORY.WO_LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_ID     IN WO_LABOR_CATEGORY.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_CLIN_ID               IN WO_LABOR_CATEGORY.CLIN_ID%TYPE DEFAULT NULL,
      P_WORK_ORDERS_ID        IN WO_LABOR_CATEGORY.WORK_ORDERS_ID%TYPE DEFAULT NULL,
      P_STD_LABOR_CATEGORY_ID IN WO_LABOR_CATEGORY.STD_LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_RATE   IN WO_LABOR_CATEGORY.LABOR_CATEGORY_RATE%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_HOURS  IN WO_LABOR_CATEGORY.LABOR_CATEGORY_HOURS%TYPE DEFAULT NULL,
      P_VENDOR                IN WO_LABOR_CATEGORY.VENDOR%TYPE DEFAULT NULL,
      P_LC_AMOUNT             IN WO_LABOR_CATEGORY.LC_AMOUNT%TYPE DEFAULT NULL,
      P_LAST_MODIFIED_BY      IN WO_LABOR_CATEGORY.LAST_MODIFIED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2);
  PROCEDURE Insert_WO_LABOR_CATEGORY(
      P_LABOR_CATEGORY_ID     IN WO_LABOR_CATEGORY.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_CLIN_ID               IN WO_LABOR_CATEGORY.CLIN_ID%TYPE DEFAULT NULL,
      P_WORK_ORDERS_ID        IN WO_LABOR_CATEGORY.WORK_ORDERS_ID%TYPE DEFAULT NULL,
      P_STD_LABOR_CATEGORY_ID IN WO_LABOR_CATEGORY.STD_LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_RATE   IN WO_LABOR_CATEGORY.LABOR_CATEGORY_RATE%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_HOURS  IN WO_LABOR_CATEGORY.LABOR_CATEGORY_HOURS%TYPE DEFAULT NULL,
      P_VENDOR                IN WO_LABOR_CATEGORY.VENDOR%TYPE DEFAULT NULL,
      P_CONTRACTOR            IN WO_LABOR_CATEGORY.CONTRACTOR%TYPE DEFAULT NULL,
      p_CREATED_BY            IN WO_LABOR_CATEGORY.LAST_MODIFIED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2);
  PROCEDURE Insert_WO_LC_SESSION(
      P_LABOR_CATEGORY_ID     IN WO_LABOR_CATEGORY.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_CLIN_ID               IN WO_LABOR_CATEGORY.CLIN_ID%TYPE DEFAULT NULL,
      p_Sub_Tasks_ID          IN WORK_ORDERS_CLINS_SESSION.SUB_TASKS_ID%TYPE DEFAULT NULL,
      P_WORK_ORDERS_ID        IN WO_LABOR_CATEGORY.WORK_ORDERS_ID%TYPE DEFAULT NULL,
      P_STD_LABOR_CATEGORY_ID IN WO_LABOR_CATEGORY.STD_LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_RATE   IN WO_LABOR_CATEGORY.LABOR_CATEGORY_RATE%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_HOURS  IN WO_LABOR_CATEGORY.LABOR_CATEGORY_HOURS%TYPE DEFAULT NULL,
      P_LC_AMOUNT             IN WO_LABOR_CATEGORY.LC_AMOUNT%TYPE DEFAULT NULL,
      P_CONTRACTOR            IN WO_LABOR_CATEGORY.CONTRACTOR%TYPE DEFAULT NULL,
      p_CREATED_BY            IN WO_LABOR_CATEGORY.LAST_MODIFIED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2);
  PROCEDURE Move_WO_LC_SESSION(
      p_WORK_ORDERS_ID IN WO_LABOR_CATEGORY.WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_CREATED_BY     IN WO_LABOR_CATEGORY.CREATED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2 ) ;
  PROCEDURE Move_ST_CLINS_SESSION(
      p_Sub_Tasks_ID             IN WORK_ORDERS_CLINS_SESSION.Sub_Tasks_ID%TYPE DEFAULT NULL,
      p_WORK_ORDERS_ID           IN WORK_ORDERS_CLINS_SESSION.FK_WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_PERIOD_OF_PERFORMANCE_ID IN WORK_ORDERS_CLINS_SESSION.FK_PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_CREATED_BY               IN WORK_ORDERS_CLINS_SESSION.CREATED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2 ) ;
  PROCEDURE Move_ST_LC_SESSION(
      p_Sub_Tasks_ID   IN WORK_ORDERS_CLINS_SESSION.Sub_Tasks_ID%TYPE DEFAULT NULL,
      p_WORK_ORDERS_ID IN WO_LABOR_CATEGORY.WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_CREATED_BY     IN WO_LABOR_CATEGORY.CREATED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2 ) ;
  PROCEDURE Delete_WO_LC_SESSION(
      p_CREATED_BY IN WO_LABOR_CATEGORY.CREATED_BY%TYPE,
      p_PStatus OUT VARCHAR2 ) ;
  PROCEDURE SP_GET_WOC(
      P_CONTRACT_NUMBER          VARCHAR2 DEFAULT NULL ,
      P_POP_TYPE                 VARCHAR2 DEFAULT NULL ,
      P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
      P_WOC_ID                   NUMBER DEFAULT 0 ,
      p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
      p_UserId                   VARCHAR2 DEFAULT NULL ,
      REC_CURSOR OUT SYS_REFCURSOR) ;
  PROCEDURE SP_GET_WO_CLINS(
      P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
      P_CLIN_ID                  VARCHAR2 DEFAULT NULL ,
      P_WOC_ID                   NUMBER DEFAULT 0 ,
      p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
      p_UserId                   VARCHAR2 DEFAULT NULL ,
      REC_CURSOR OUT SYS_REFCURSOR);
PROCEDURE SP_GET_WO_CLINS_SESS(
    P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
    P_CLIN_ID                  NUMBER DEFAULT NULL ,
    P_WOC_ID                   NUMBER DEFAULT 0 ,
    p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
    p_UserId                   VARCHAR2 DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_CLINS_List(
      P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
      P_CLIN_ID                  NUMBER DEFAULT NULL ,
      P_CLIN_TYPE                VARCHAR2 DEFAULT NULL,
  --    P_WOC_ID                   NUMBER DEFAULT 0 ,
    --  p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
      p_UserId                   VARCHAR2 DEFAULT NULL ,      
      REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE sp_get_Work_Orders(
      p_UserId          VARCHAR2 DEFAULT NULL,
      P_WORK_ORDERS_ID  NUMBER DEFAULT 0 ,
      P_POP_ID          NUMBER DEFAULT 0 ,
      p_contract_number VARCHAR2 DEFAULT NULL,
      REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE sp_get_TO_DETAILS(
      p_UserId         VARCHAR2,
      P_WORK_ORDERS_ID NUMBER DEFAULT 0,
      REC_CURSOR OUT SYS_REFCURSOR) ;
  PROCEDURE sp_get_TOs(
      p_UserId          VARCHAR2,
      P_POP_ID          VARCHAR2 DEFAULT NULL,
      p_contract_number VARCHAR2 ,
      --  P_WORK_ORDERS_ID number default 0,
      REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_WO_CLIN_DETAILS(
      P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
      P_CLIN_ID                  VARCHAR2 DEFAULT NULL ,
      P_WOC_ID                   NUMBER DEFAULT 0 ,
      p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
      p_UserId                   VARCHAR2 DEFAULT NULL ,
      REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE sp_get_WO_LABOR_CATEGORY(
      p_WO_LABOR_CATEGORY_ID VARCHAR2 DEFAULT 0,
      p_WORK_ORDERS_ID       VARCHAR2 DEFAULT NULL,
      p_LABOR_CATEGORY_ID    VARCHAR2 DEFAULT 0,
      p_CLIN_ID              VARCHAR2 DEFAULT NULL,
      p_USER                 VARCHAR2 DEFAULT NULL,
      REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_WOC_TYPE_COUNTS(
      p_UserId         VARCHAR2 DEFAULT NULL,
      p_WORK_ORDERS_ID NUMBER DEFAULT 0 ,
      REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_TO_ST_CLINS(
      P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
      P_CLIN_ID                  VARCHAR2 DEFAULT NULL ,
      P_WOC_ID                   NUMBER DEFAULT 0 ,
      p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
      p_UserId                   VARCHAR2 DEFAULT NULL ,
      REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_ORG_TITLE(
      P_ORG_CODE IN VARCHAR2 ,
      p_org_title OUT VARCHAR2 ) ;
FUNCTION FN_GET_ORG_TITLE_FROM_SP(
    p_OrgCode VARCHAR2)
  RETURN VARCHAR2;  
PROCEDURE sp_get_TO_STs(
    p_UserId  varchar2,
    P_POP_ID varchar2 default NULL,
    p_contract_number  varchar2 ,
    TO_REC_CURSOR OUT SYS_REFCURSOR )  ;
PROCEDURE sp_get_TO_STsX(
    p_UserId  varchar2,
    P_POP_ID varchar2 default NULL,
    p_contract_number  varchar2 ,
    TO_REC_CURSOR OUT SYS_REFCURSOR,
    ST_REC_CURSOR OUT SYS_REFCURSOR)  ;
PROCEDURE SP_GET_TASKCLIN_BREAKOUTS(
    P_CONTRACT_NUMBER          VARCHAR2 DEFAULT NULL ,
    P_POP_TYPE                 VARCHAR2 DEFAULT NULL ,
    P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
    P_WOC_ID                   NUMBER DEFAULT 0 ,
    p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
    p_UserId                   VARCHAR2 DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR); 
PROCEDURE sp_get_Contract_TOs(
    p_UserId  varchar2,
    P_POP_ID varchar2, 
    p_contract_number  varchar2 ,
    REC_CURSOR OUT SYS_REFCURSOR);
  PROCEDURE Delete_WO_ID_CLINS_SESSION(
      p_CREATED_BY IN WORK_ORDERS_CLINS_SESSION.CREATED_BY%TYPE ,
      p_WORK_ORDERS_ID IN WORK_ORDERS_CLINS_SESSION.CREATED_BY%TYPE ,
      p_PStatus OUT VARCHAR2 )   ;     
  PROCEDURE SP_GET_WO_CLINS_SESS_NEW(
    P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
    P_CLIN_ID                  NUMBER DEFAULT NULL ,
    P_WOC_ID                   NUMBER DEFAULT 0 ,
    p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
    p_UserId                   VARCHAR2 DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR);
END pkg_work_orders;
/