CREATE OR REPLACE PACKAGE eemrt.PKG_DELIVERABLES
AS
  /*
  Procedure : PKG_DELIVERABLES
  Author: Sridhar Kommana
  Date Created : 01/27/2016
  Purpose: Select Insert Update Delete DELIVERABLES records for eCert
  Update history:
  */
  PROCEDURE SP_GET_DELIVERABLES(
      P_CONTRACT_NUMBER VARCHAR2 DEFAULT NULL ,
      p_WORK_ORDERS_ID  NUMBER DEFAULT 0 ,
      P_SUB_TASKS_ID    NUMBER DEFAULT 0 ,
      P_DELIVERABLE_ID DELIVERABLES.DELIVERABLE_ID%TYPE DEFAULT 0 ,
      P_DELIVERABLE_STATUS DELIVERABLES.DELIVERABLE_STATUS%TYPE DEFAULT NULL,
      p_UserId VARCHAR2 ,
      REC_CURSOR OUT SYS_REFCURSOR) ;
  PROCEDURE SP_GET_DELIVERABLE_DETAILS(
      P_CONTRACT_NUMBER VARCHAR2 DEFAULT NULL ,
      p_WORK_ORDERS_ID  NUMBER DEFAULT 0 ,
      P_SUB_TASKS_ID    NUMBER DEFAULT 0 ,
      P_DELIVERABLE_ID DELIVERABLES.DELIVERABLE_ID%TYPE DEFAULT 0 ,
      P_DELIVERABLE_DETAIL_ID NUMBER DEFAULT 0 ,
      P_DELIVERABLE_STATUS DELIVERABLES.DELIVERABLE_STATUS%TYPE DEFAULT NULL,
      p_UserId VARCHAR2 ,
      REC_CURSOR OUT SYS_REFCURSOR) ;
  PROCEDURE sp_insert_deliverables(
      P_DELIVERABLE_NUMBER DELIVERABLES.DELIVERABLE_NUMBER%TYPE,
      P_DELIVERABLE_TYPE DELIVERABLES.DELIVERABLE_TYPE%TYPE,
      P_DELIVERABLE_TITLE DELIVERABLES.DELIVERABLE_TITLE%TYPE,
      P_DUE_DATE_FREQUNCY DELIVERABLES.DUE_DATE_FREQUNCY%TYPE,
      P_ACCEPTANCE_CRITERIA DELIVERABLES.ACCEPTANCE_CRITERIA%TYPE,
      P_TECHNICAL_REVIEWER DELIVERABLES.TECHNICAL_REVIEWER%TYPE,
      P_DELIVERABLE_STATUS DELIVERABLES.DELIVERABLE_STATUS%TYPE,
      P_INSTRUCTIONS DELIVERABLES.INSTRUCTIONS%TYPE,
      P_WORK_ORDERS_ID DELIVERABLES.WORK_ORDERS_ID%TYPE,
      P_SUB_TASKS_ID DELIVERABLES.SUB_TASKS_ID%TYPE,
      P_CONTRACT_NUMBER DELIVERABLES.CONTRACT_NUMBER%TYPE,
      P_VENDOR DELIVERABLES.VENDOR%TYPE,
      P_CO_NAME DELIVERABLES.CO_NAME%TYPE,
      P_COR_NAME DELIVERABLES.COR_NAME%TYPE,
      P_TECHNICAL_REVIEWER_ID DELIVERABLES.TECHNICAL_REVIEWER_ID%TYPE,
      P_CO_ID DELIVERABLES.CO_ID%TYPE,
      P_COR_ID DELIVERABLES.COR_ID%TYPE,
      P_TASK_INFO DELIVERABLES.TASK_INFO%TYPE,
      P_CREATED_BY DELIVERABLES.CREATED_BY%TYPE,
      P_CREATED_ON DELIVERABLES.CREATED_ON%TYPE,
      p_id OUT DELIVERABLES.DELIVERABLE_ID%type,
      p_PStatus OUT VARCHAR2);
  PROCEDURE sp_update_deliverables(
      P_DELIVERABLE_ID DELIVERABLES.DELIVERABLE_ID%TYPE,
      P_DELIVERABLE_NUMBER DELIVERABLES.DELIVERABLE_NUMBER%TYPE,
      P_DELIVERABLE_TYPE DELIVERABLES.DELIVERABLE_TYPE%TYPE,
      P_DELIVERABLE_TITLE DELIVERABLES.DELIVERABLE_TITLE%TYPE,
      P_DUE_DATE_FREQUNCY DELIVERABLES.DUE_DATE_FREQUNCY%TYPE,
      P_ACCEPTANCE_CRITERIA DELIVERABLES.ACCEPTANCE_CRITERIA%TYPE,
      P_TECHNICAL_REVIEWER DELIVERABLES.TECHNICAL_REVIEWER%TYPE,
      P_TECHNICAL_REVIEWER_ID DELIVERABLES.TECHNICAL_REVIEWER_ID%TYPE,
      P_DELIVERABLE_STATUS DELIVERABLES.DELIVERABLE_STATUS%TYPE,
      P_INSTRUCTIONS DELIVERABLES.INSTRUCTIONS%TYPE,
      P_WORK_ORDERS_ID DELIVERABLES.WORK_ORDERS_ID%TYPE,
      P_SUB_TASKS_ID DELIVERABLES.SUB_TASKS_ID%TYPE,
      P_TASK_INFO DELIVERABLES.TASK_INFO%TYPE,      
      P_Updated_BY DELIVERABLES.Updated_by%TYPE,
      P_Updated_ON DELIVERABLES.Updated_on%TYPE,
      p_PStatus OUT VARCHAR2);
  PROCEDURE sp_submit_deliverable(
      P_DELIVERABLE_ID DELIVERABLES.DELIVERABLE_ID%TYPE,
      P_FYI_NOTIFICATION DELIVERABLES.FYI_NOTIFICATION%TYPE,
      P_SUBMITTED_BY DELIVERABLE_DETAIL.SUBMITTED_BY%TYPE,
      P_SUBMISSION_TITLE DELIVERABLE_DETAIL.SUBMISSION_TITLE%TYPE,
      P_COMMENTS DELIVERABLE_DETAIL.COMMENTS%TYPE,
      P_Temp_id VARCHAR2,
      p_id OUT DELIVERABLES.DELIVERABLE_ID%type,
      p_PStatus OUT VARCHAR2);
  PROCEDURE sp_get_COs_CORs(
      p_UserId          VARCHAR2,
      p_CONTRACT_NUMBER VARCHAR2,
      COR_cursor OUT SYS_REFCURSOR);
  PROCEDURE SP_GET_TR_ROUTINGS(
      P_CONTRACT_NUMBER DELIVERABLE_DETAIL.CONTRACT_NUMBER%TYPE,
      P_DELIVERABLE_TR_ROUTING_ID NUMBER DEFAULT 0 ,
      P_DELIVERABLE_ID DELIVERABLES.DELIVERABLE_ID%TYPE DEFAULT 0 ,
      P_DELIVERABLE_DETAIL_ID NUMBER DEFAULT 0 ,
      P_DELIVERABLE_STATUS DELIVERABLES.DELIVERABLE_STATUS%TYPE DEFAULT NULL,
      P_TECHNICAL_REVIEWER_ID DELIVERABLES.TECHNICAL_REVIEWER_ID%TYPE DEFAULT NULL,
      p_UserId VARCHAR2 ,
      REC_CURSOR OUT SYS_REFCURSOR) ;
  PROCEDURE sp_Review_deliverable(
      P_DELIVERABLE_TR_ROUTING_ID NUMBER ,
      P_Rating DELIVERABLE_TR_ROUTING.Rating%TYPE DEFAULT NULL,
      P_Comments DELIVERABLE_TR_ROUTING.Comments%TYPE DEFAULT NULL,
      p_UserId VARCHAR2,
      p_PStatus OUT VARCHAR2);
  PROCEDURE SP_GET_COR_ROUTINGS(
      P_CONTRACT_NUMBER DELIVERABLE_DETAIL.CONTRACT_NUMBER%TYPE,
      P_DELIVERABLE_COR_ROUTING_ID NUMBER DEFAULT 0 ,
      P_DELIVERABLE_ID DELIVERABLES.DELIVERABLE_ID%TYPE DEFAULT 0 ,
      P_DELIVERABLE_DETAIL_ID NUMBER DEFAULT 0 ,
      P_DELIVERABLE_ROUTING_STATUS DELIVERABLE_COR_ROUTING.DELIVERABLE_STATUS%TYPE DEFAULT NULL,
      P_DELIVERABLE_DETAIL_STATUS DELIVERABLE_Detail.DELIVERABLE_STATUS%TYPE DEFAULT NULL,            
      P_COR_ID DELIVERABLES.COR_ID%TYPE DEFAULT NULL,
      p_UserId VARCHAR2 ,
      REC_CURSOR OUT SYS_REFCURSOR) ;
  PROCEDURE sp_Accept_deliverable(
      P_DELIVERABLE_COR_ROUTING_ID NUMBER ,
      P_Status DELIVERABLE_COR_ROUTING.Deliverable_Status%TYPE DEFAULT NULL,
      P_Comments DELIVERABLE_COR_ROUTING.Comments%TYPE DEFAULT NULL,
      P_CO_APPROVAL DELIVERABLE_COR_ROUTING.CO_APPROVAL%TYPE DEFAULT 'N',
      p_ACCEPT  DELIVERABLE_COR_ROUTING.ACCEPT%TYPE DEFAULT 'N',
      p_CO_ID DELIVERABLE_CO_ROUTING.CO_ID%TYPE DEFAULT NULL,      
      --P_userRole VARCHAR2,
      p_UserId   VARCHAR2,
      p_PStatus OUT VARCHAR2);
  PROCEDURE SP_GET_CO_ROUTINGS(
      P_CONTRACT_NUMBER DELIVERABLE_DETAIL.CONTRACT_NUMBER%TYPE,
      P_DELIVERABLE_CO_ROUTING_ID NUMBER DEFAULT 0 ,
      P_DELIVERABLE_ID DELIVERABLES.DELIVERABLE_ID%TYPE DEFAULT 0 ,
      P_DELIVERABLE_DETAIL_ID NUMBER DEFAULT 0 ,
      P_DELIVERABLE_ROUTING_STATUS DELIVERABLE_CO_ROUTING.DELIVERABLE_STATUS%TYPE DEFAULT NULL,
      P_DELIVERABLE_DETAIL_STATUS DELIVERABLE_Detail.DELIVERABLE_STATUS%TYPE DEFAULT NULL,            
      P_CO_ID DELIVERABLES.CO_ID%TYPE DEFAULT NULL,
      p_UserId VARCHAR2 ,
      REC_CURSOR OUT SYS_REFCURSOR) ;
  PROCEDURE sp_Approve_deliverable(
      P_DELIVERABLE_CO_ROUTING_ID NUMBER ,
      P_Status DELIVERABLE_CO_ROUTING.Deliverable_Status%TYPE,
      P_Comments DELIVERABLE_CO_ROUTING.Comments%TYPE DEFAULT NULL,
      P_APPROVE DELIVERABLE_CO_ROUTING.APPROVE%TYPE, 
      p_UserId   VARCHAR2,
      p_PStatus OUT VARCHAR2);
END PKG_DELIVERABLES;
/