CREATE OR REPLACE PACKAGE eemrt.pkg_SUB_TASKS
IS
 
  /*
  Package  : pkg_SUB_TASKS
  Author: Sridhar Kommana
  Date Created : 08/06/2015
  Purpose:  Insert Update Delete Sub Task and related tables  for eCert
  Update history:
 
*/
  -- Insert_SUB_TASKS
  PROCEDURE insert_SUB_TASKS(
      p_WORK_ORDERS_ID        IN SUB_TASKS.WORK_ORDERS_ID%TYPE DEFAULT NULL,
      p_SUB_TASK_NUMBER        IN SUB_TASKS.SUB_TASK_NUMBER%TYPE DEFAULT NULL,
      p_SUB_TASK_TITLE         IN SUB_TASKS.SUB_TASK_TITLE%TYPE DEFAULT NULL,
      p_START_DATE               IN SUB_TASKS.START_DATE%TYPE DEFAULT NULL,
      p_END_DATE                 IN SUB_TASKS.END_DATE%TYPE DEFAULT NULL,
      p_DESCRIPTION              IN SUB_TASKS.DESCRIPTION%TYPE DEFAULT NULL,
      p_ORGANIZATION             IN SUB_TASKS.ORGANIZATION%TYPE DEFAULT NULL,
      p_FAA_POC                  IN SUB_TASKS.FAA_POC%TYPE DEFAULT NULL,
      p_PERIOD_OF_PERFORMANCE_ID IN SUB_TASKS.PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_Status                   IN SUB_TASKS.Status%TYPE DEFAULT NULL,
      p_ST_FEE                   IN SUB_TASKS.ST_FEE%TYPE DEFAULT 0,      
      p_CREATED_BY               IN SUB_TASKS.CREATED_BY%TYPE DEFAULT NULL,
      p_ID OUT SUB_TASKS.SUB_TASKS_ID%TYPE,
      p_PStatus OUT VARCHAR2 );
  -- update_SUB_TASKS
  PROCEDURE Update_SUB_TASKS(
  
      p_SUB_TASKS_ID        IN SUB_TASKS.SUB_TASKS_ID%TYPE DEFAULT NULL,      
      p_SUB_TASK_NUMBER        IN SUB_TASKS.SUB_TASK_NUMBER%TYPE DEFAULT NULL,
      p_SUB_TASK_TITLE         IN SUB_TASKS.SUB_TASK_TITLE%TYPE DEFAULT NULL,
      p_START_DATE               IN SUB_TASKS.START_DATE%TYPE DEFAULT NULL,
      p_END_DATE                 IN SUB_TASKS.END_DATE%TYPE DEFAULT NULL,
      p_DESCRIPTION              IN SUB_TASKS.DESCRIPTION%TYPE DEFAULT NULL,
      p_ORGANIZATION             IN SUB_TASKS.ORGANIZATION%TYPE DEFAULT NULL,
      p_FAA_POC                  IN SUB_TASKS.FAA_POC%TYPE DEFAULT NULL,      
      p_Status                   IN SUB_TASKS.Status%TYPE DEFAULT NULL,
      p_ST_FEE                   IN SUB_TASKS.ST_FEE%TYPE DEFAULT 0,      
      P_LAST_MODIFIED_BY         IN SUB_TASKS.LAST_MODIFIED_BY%TYPE DEFAULT NULL,      
      p_PStatus OUT VARCHAR2 );
 PROCEDURE SP_GET_STCLINS(
    P_SubTaskID                   NUMBER DEFAULT 0 ,
    p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
    p_UserId                   VARCHAR2 DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR); 

PROCEDURE SP_GET_STC_TYPE_COUNTS(
    p_UserId       VARCHAR2 DEFAULT NULL,
    p_SUB_TASKS_ID NUMBER DEFAULT 0 ,
    -- p_WORK_ORDERS_ID NUMBER DEFAULT 0 ,
    REC_CURSOR OUT SYS_REFCURSOR);
PROCEDURE       sp_get_Sub_Task_Orders(
    p_UserId  varchar2 DEFAULT NULL,
    P_SUB_TASKS_ID NUMBER DEFAULT 0 ,
    P_Work_Orders_ID NUMBER DEFAULT 0 ,
    REC_CURSOR OUT SYS_REFCURSOR);      

PROCEDURE SP_GET_SUB_TASK_INFO(
          p_UserId  varchar2 ,
          P_Work_Orders_ID NUMBER DEFAULT 0 ,
          REC_CURSOR OUT SYS_REFCURSOR);

PROCEDURE Delete_SUB_TASKS(
      p_SUB_TASKS_ID        IN SUB_TASKS.SUB_TASKS_ID%TYPE DEFAULT NULL,      
      P_LAST_MODIFIED_BY         IN SUB_TASKS.LAST_MODIFIED_BY%TYPE DEFAULT NULL,      
      p_PStatus OUT VARCHAR2 );    
END pkg_SUB_TASKS;
/