CREATE OR REPLACE PACKAGE eemrt."PKG_SUB_CONTRACTOR" 
IS
 
  /*
  Procedure : PKG_SUB_CONTRACTOR
  Author: Sridhar Kommana
  Date Created : 07/13/2015
  Purpose:  Insert Update Delete Sub Contractor records for eCert
  Update history:
 
*/
  PROCEDURE INSERT_SUB_CONTRACTOR(

      p_VENDOR_NAME            IN SUB_CONTRACTOR.VENDOR_NAME%TYPE DEFAULT NULL,
      p_CONTRACT_NUMBER                IN SUB_CONTRACTOR.CONTRACT_NUMBER%TYPE DEFAULT NULL,
      p_POC_FNAME            IN SUB_CONTRACTOR.POC_FNAME%TYPE DEFAULT NULL,
      p_POC_LNAME               IN SUB_CONTRACTOR.POC_LNAME%TYPE DEFAULT NULL,
      p_POC_MNAME               IN SUB_CONTRACTOR.POC_MNAME%TYPE DEFAULT NULL,
      p_SMALL_BUSINESS                IN SUB_CONTRACTOR.SMALL_BUSINESS%TYPE DEFAULT NULL,
      p_CREATED_BY               IN SUB_CONTRACTOR.CREATED_BY%TYPE DEFAULT NULL,
      p_ID OUT SUB_CONTRACTOR.SUB_CONTRACTOR_ID%TYPE,          
      p_PStatus OUT VARCHAR2);
  PROCEDURE UPDATE_SUB_CONTRACTOR(
      p_SUB_CONTRACTOR_ID IN SUB_CONTRACTOR.SUB_CONTRACTOR_ID%TYPE DEFAULT NULL,
      p_VENDOR_NAME            IN SUB_CONTRACTOR.VENDOR_NAME%TYPE DEFAULT NULL,
      p_CONTRACT_NUMBER                IN SUB_CONTRACTOR.CONTRACT_NUMBER%TYPE DEFAULT NULL,
      p_POC_FNAME            IN SUB_CONTRACTOR.POC_FNAME%TYPE DEFAULT NULL,
      p_POC_LNAME               IN SUB_CONTRACTOR.POC_LNAME%TYPE DEFAULT NULL,
      p_POC_MNAME               IN SUB_CONTRACTOR.POC_MNAME%TYPE DEFAULT NULL,
      p_SMALL_BUSINESS                IN SUB_CONTRACTOR.SMALL_BUSINESS%TYPE DEFAULT NULL,
      p_LAST_MODIFIED_BY               IN SUB_CONTRACTOR.CREATED_BY%TYPE DEFAULT NULL,      
      p_PStatus OUT VARCHAR2);      
  PROCEDURE DELETE_SUB_CONTRACTOR(
      p_SUB_CONTRACTOR_ID IN SUB_CONTRACTOR.SUB_CONTRACTOR_ID%TYPE DEFAULT NULL,
      p_LAST_MODIFIED_BY               IN SUB_CONTRACTOR.CREATED_BY%TYPE DEFAULT NULL,      
      p_PStatus OUT VARCHAR2);         
 PROCEDURE       SP_GET_SUB_CONTRACTOR(
    p_UserId     varchar2 DEFAULT NULL ,
    p_SUB_CONTRACTOR_ID     NUMBER DEFAULT 0 ,
    p_VENDOR_NAME  varchar2 DEFAULT NULL ,
    p_CONTRACT_NUMBER  varchar2 DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR);
 PROCEDURE   SP_GET_CONTRACTORS(
    p_UserId     varchar2 DEFAULT NULL ,
    p_CONTRACTOR_ID     NUMBER DEFAULT 0 ,
      p_CONTRACT_NUMBER VARCHAR2, 
    REC_CURSOR OUT SYS_REFCURSOR);    
  
  PROCEDURE SP_GET_CONTRACTORS_T(
      p_UserId        VARCHAR2 DEFAULT NULL ,
      p_CONTRACTOR_ID NUMBER DEFAULT 0 ,
      p_CONTRACT_NUMBER VARCHAR2,
      REC_CURSOR OUT SYS_REFCURSOR)    ;
  PROCEDURE SP_INSERT_CONTRACTOR_T(
          p_CREATED_BY CONTRACTORS_T.CREATED_BY%TYPE, 
          p_FIRST_NAME CONTRACTORS_T.FIRST_NAME%TYPE,
          p_MIDDLE_NAME CONTRACTORS_T.MIDDLE_NAME%TYPE,
          p_LAST_NAME CONTRACTORS_T.LAST_NAME%TYPE,
          p_EMAIL CONTRACTORS_T.EMAIL%TYPE,
          p_VENDOR CONTRACTORS_T.VENDOR%TYPE,
          p_CONTRACT_NUMBER CONTRACTORS_T.CONTRACT_NUMBER%TYPE,
          p_ID OUT CONTRACTORS_T.CONTRACTOR_ID%TYPE,
          p_PStatus OUT VARCHAR2);  

  PROCEDURE SP_UPDATE_CONTRACTOR_T(
          p_userid CONTRACTORS_T.CREATED_BY%TYPE, 
          p_CONTRACTOR_ID CONTRACTORS_T.CONTRACTOR_ID%TYPE,          
          p_FIRST_NAME CONTRACTORS_T.FIRST_NAME%TYPE,
          p_MIDDLE_NAME CONTRACTORS_T.MIDDLE_NAME%TYPE,
          p_LAST_NAME CONTRACTORS_T.LAST_NAME%TYPE,
          p_EMAIL CONTRACTORS_T.EMAIL%TYPE,
          p_VENDOR CONTRACTORS_T.VENDOR%TYPE,
          p_CONTRACT_NUMBER CONTRACTORS_T.CONTRACT_NUMBER%TYPE,          
          p_PStatus OUT VARCHAR2);  
  PROCEDURE Delete_CONTRACTOR_T(
      p_UserId        VARCHAR2 ,
      p_CONTRACTOR_ID    IN CONTRACTORS_T.CONTRACTOR_ID%TYPE,
      p_PStatus OUT VARCHAR2
      );           
                    
  PROCEDURE SP_GET_CONTRACTORS_TOS(
      p_UserId        VARCHAR2 DEFAULT NULL ,
      p_CONTRACTOR_ID NUMBER DEFAULT 0 ,
      P_CONTRACTOR_TOID NUMBER DEFAULT 0 ,
      REC_CURSOR OUT SYS_REFCURSOR);    
      
  PROCEDURE INSERT_TASK_CONTRACTORS(
      p_CONTRACTOR_ID         IN TASK_CONTRACTORS.CONTRACTOR_ID%TYPE DEFAULT NULL,
      p_WORK_ORDER_ID         IN TASK_CONTRACTORS.WORK_ORDER_ID%TYPE DEFAULT NULL,
      p_SUBTASK_ID            IN TASK_CONTRACTORS.SUBTASK_ID%TYPE DEFAULT NULL,
      p_CLIN_ID               IN TASK_CONTRACTORS.CLIN_ID%TYPE DEFAULT NULL,
      p_SUB_CLIN_ID           IN TASK_CONTRACTORS.SUB_CLIN_ID%TYPE DEFAULT NULL,      
      p_LABOR_CATEGORY_ID     IN TASK_CONTRACTORS.LABOR_CATEGORY_ID%TYPE DEFAULT NULL, 
      p_WOC_ID     IN TASK_CONTRACTORS.WOC_ID%TYPE DEFAULT NULL, 
      p_STC_ID     IN TASK_CONTRACTORS.STC_ID%TYPE DEFAULT NULL,       
      p_CREATED_BY      IN TASK_CONTRACTORS.CREATED_BY%TYPE DEFAULT NULL,      
      p_PStatus OUT VARCHAR2
      );      
  PROCEDURE Update_TASK_CONTRACTORS(
      p_TASK_CONTRACTOR_ID    IN TASK_CONTRACTORS.TASK_CONTRACTOR_ID%TYPE DEFAULT NULL,
      p_CONTRACTOR_ID         IN TASK_CONTRACTORS.CONTRACTOR_ID%TYPE DEFAULT NULL, 
      p_WORK_ORDER_ID         IN TASK_CONTRACTORS.WORK_ORDER_ID%TYPE DEFAULT NULL,
      p_SUBTASK_ID            IN TASK_CONTRACTORS.SUBTASK_ID%TYPE DEFAULT NULL,
      p_CLIN_ID               IN TASK_CONTRACTORS.CLIN_ID%TYPE DEFAULT NULL,
      p_SUB_CLIN_ID           IN TASK_CONTRACTORS.SUB_CLIN_ID%TYPE DEFAULT NULL,      
      p_LABOR_CATEGORY_ID     IN TASK_CONTRACTORS.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      p_Updated_BY            IN TASK_CONTRACTORS.Updated_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2
      );       
  PROCEDURE Delete_TASK_CONTRACTORS(
      p_UserId        VARCHAR2 ,
      p_TASK_CONTRACTOR_ID    IN TASK_CONTRACTORS.TASK_CONTRACTOR_ID%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2
      );       
  PROCEDURE SP_GET_TASK_CONTRACTORS(
      p_UserId        VARCHAR2 DEFAULT NULL ,
      p_CONTRACTOR_ID NUMBER DEFAULT 0 ,
      p_TASK_CONTRACTOR_ID NUMBER DEFAULT 0 ,
      REC_CURSOR OUT SYS_REFCURSOR);    
  PROCEDURE SP_GET_All_TASK_CONTRACTORS(
      p_UserId        VARCHAR2 DEFAULT NULL ,
      p_CONTRACT_NUMBER VARCHAR2 DEFAULT NULL ,
      p_WORK_ORDER_ID         IN TASK_CONTRACTORS.WORK_ORDER_ID%TYPE DEFAULT 0,
      p_SUBTASK_ID            IN TASK_CONTRACTORS.SUBTASK_ID%TYPE DEFAULT 0,      
      p_CLIN_ID NUMBER  DEFAULT 0,
      p_SUB_CLIN_ID NUMBER DEFAULT 0,
      p_LABOR_CATEGORY_ID  NUMBER  DEFAULT 0,         
      REC_CURSOR OUT SYS_REFCURSOR);    
  PROCEDURE SP_GET_CLIN_TASK_CONTRACTORS(
      p_UserId        VARCHAR2 DEFAULT NULL ,
      p_CONTRACT_NUMBER VARCHAR2 DEFAULT NULL ,
      p_WORK_ORDER_ID         IN TASK_CONTRACTORS.WORK_ORDER_ID%TYPE DEFAULT 0,
      p_SUBTASK_ID            IN TASK_CONTRACTORS.SUBTASK_ID%TYPE DEFAULT 0,
      p_CLIN_ID NUMBER  DEFAULT 0,
      p_SUB_CLIN_ID NUMBER DEFAULT 0,
      p_LABOR_CATEGORY_ID  NUMBER  DEFAULT 0,              
      REC_CURSOR OUT SYS_REFCURSOR) ; 
 PROCEDURE SP_GET_Travel_TASK_CONTRACTORS(
      p_UserId        VARCHAR2 DEFAULT NULL ,
      p_CONTRACT_NUMBER VARCHAR2 DEFAULT NULL ,
      p_WORK_ORDER_ID         IN TASK_CONTRACTORS.WORK_ORDER_ID%TYPE DEFAULT 0,
      p_SUBTASK_ID            IN TASK_CONTRACTORS.SUBTASK_ID%TYPE DEFAULT 0,
      p_CLIN_ID NUMBER  DEFAULT 0,
      p_SUB_CLIN_ID NUMBER DEFAULT 0,
      p_LABOR_CATEGORY_ID  NUMBER  DEFAULT 0,              
      REC_CURSOR OUT SYS_REFCURSOR) ;
PROCEDURE SP_UPDATE_SUBCONTRACTOR_CODES 
(
    P_SUBCONTRACTORID IN SUB_CONTRACTOR.SUB_CONTRACTOR_ID%TYPE
  , P_SMALL_BUSINESS_CODES IN SUB_CONTRACTOR.SMALL_BUSINESS%TYPE
  , P_CONTRACT_NUMBER IN SUB_CONTRACTOR.CONTRACT_NUMBER%TYPE
  , P_USERID IN SUB_CONTRACTOR.CREATED_BY%TYPE 
  , P_PSTATUS OUT VARCHAR2 
);

 END PKG_SUB_CONTRACTOR;
/