CREATE OR REPLACE PACKAGE eemrt."PKG_SUB_CLIN" 
IS


  PROCEDURE insert_SUB_CLIN(
    p_SUB_CLIN_NUMBER  IN SUB_CLIN.SUB_CLIN_NUMBER%type DEFAULT NULL,
    p_CLIN_ID  IN SUB_CLIN.CLIN_ID%type DEFAULT NULL,
    p_SUB_CLIN_TITLE  IN SUB_CLIN.SUB_CLIN_TITLE%type DEFAULT NULL,
    p_SUB_CLIN_TYPE IN SUB_CLIN.SUB_CLIN_TYPE%TYPE,
    p_SUB_CLIN_HOURS  IN SUB_CLIN.SUB_CLIN_HOURS%type DEFAULT NULL,
    p_SUB_CLIN_RATE  IN SUB_CLIN.SUB_CLIN_RATE%type DEFAULT NULL,
    p_SUB_CLIN_AMOUNT  IN SUB_CLIN.SUB_CLIN_AMOUNT%type DEFAULT NULL,
    p_LABOR_CATEGORY_ID IN SUB_CLIN.LABOR_CATEGORY_ID%type DEFAULT NULL,
    p_LABOR_RATE_TYPE      IN SUB_CLIN.LABOR_RATE_TYPE%TYPE DEFAULT NULL,    
    p_CREATED_BY IN SUB_CLIN.CREATED_BY%type DEFAULT NULL,
    p_PStatus                   OUT VARCHAR2);
   
  PROCEDURE update_SUB_CLIN(
    p_SUB_CLIN_ID       IN SUB_CLIN.SUB_CLIN_ID%type DEFAULT NULL,
    p_SUB_CLIN_NUMBER   IN SUB_CLIN.SUB_CLIN_NUMBER%type DEFAULT NULL,
    p_SUB_CLIN_TITLE    IN SUB_CLIN.SUB_CLIN_TITLE%type DEFAULT NULL,
    p_SUB_CLIN_TYPE     IN SUB_CLIN.SUB_CLIN_TYPE%TYPE,
    p_SUB_CLIN_HOURS    IN SUB_CLIN.SUB_CLIN_HOURS%type DEFAULT NULL,
    p_SUB_CLIN_RATE     IN SUB_CLIN.SUB_CLIN_RATE%type DEFAULT NULL,
    p_SUB_CLIN_AMOUNT   IN SUB_CLIN.SUB_CLIN_AMOUNT%type DEFAULT NULL,
    p_LABOR_CATEGORY_ID IN SUB_CLIN.LABOR_CATEGORY_ID%type DEFAULT NULL,
    p_LABOR_RATE_TYPE      IN SUB_CLIN.LABOR_RATE_TYPE%TYPE DEFAULT NULL,      
    p_LAST_MODIFIED_BY  IN SUB_CLIN.LAST_MODIFIED_BY%type DEFAULT NULL ,
    p_PStatus OUT VARCHAR2 );

  PROCEDURE delete_SUB_CLIN(
      p_SUB_CLIN_ID IN SUB_CLIN.SUB_CLIN_ID%type,
      p_PStatus                   OUT VARCHAR2  );
      PROCEDURE       SP_GET_SUB_CLIN_INFO(
    p_UserId     varchar2 DEFAULT NULL ,
    P_CLIN_ID number DEFAULT 0 ,
    REC_CURSOR OUT SYS_REFCURSOR)    ;

PROCEDURE       SP_GET_SUB_CLIN(
    p_UserId     varchar2 DEFAULT NULL ,
    P_CLIN_ID     NUMBER DEFAULT 0 ,
    P_SUB_CLIN_ID NUMBER DEFAULT 0 ,
    REC_CURSOR OUT SYS_REFCURSOR);
    
END PKG_SUB_CLIN;
/