CREATE OR REPLACE PACKAGE eemrt."PKG_POP_CLIN" 
IS
   PROCEDURE insert_POP_CLIN (
      p_PERIOD_OF_PERFORMANCE_ID   IN     POP_CLIN.PERIOD_OF_PERFORMANCE_ID%TYPE DEFAULT NULL,
      p_CLIN_NUMBER                IN     POP_CLIN.CLIN_NUMBER%TYPE DEFAULT NULL,
      p_CLIN_TYPE                  IN     POP_CLIN.CLIN_TYPE%TYPE DEFAULT NULL,
      p_CLIN_SUB_CLIN              IN     POP_CLIN.CLIN_SUB_CLIN%TYPE DEFAULT NULL,
      p_CLIN_TITLE                 IN     POP_CLIN.CLIN_TITLE%TYPE DEFAULT NULL,
      p_CLIN_HOURS                 IN     POP_CLIN.CLIN_HOURS%TYPE DEFAULT NULL,
      p_CLIN_RATE                  IN     POP_CLIN.CLIN_RATE%TYPE DEFAULT NULL,
      p_CLIN_AMOUNT                IN     POP_CLIN.CLIN_AMOUNT%TYPE DEFAULT NULL,
      p_HOURS_COMMITED             IN     POP_CLIN.HOURS_COMMITED%TYPE DEFAULT NULL,
      p_LABOR_CATEGORY_ID          IN     SUB_CLIN.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      p_HASLABORCATEGORIES         IN     POP_CLIN.HASLABORCATEGORIES%TYPE DEFAULT NULL,
      p_LABOR_RATE_TYPE            IN     POP_CLIN.LABOR_RATE_TYPE%TYPE DEFAULT NULL,
      p_RATE_TYPE                  IN     POP_CLIN.RATE_TYPE%TYPE DEFAULT NULL,
      p_CREATED_BY                 IN     POP_CLIN.CREATED_BY%TYPE DEFAULT NULL,
      p_Labor_Amount               IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,
      p_Travel_Amount              IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,
      p_Material_Amount            IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,
      p_ODC_Amount                 IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,        
      p_ID                         OUT work_orders.WORK_ORDERS_ID%TYPE,
      p_PStatus                    OUT VARCHAR2);
  
  -- update_POP_CLINate
  PROCEDURE update_POP_CLIN(
      p_CLIN_ID           IN POP_CLIN.CLIN_ID%TYPE DEFAULT NULL,
      p_CLIN_NUMBER       IN POP_CLIN.CLIN_NUMBER%TYPE DEFAULT NULL,
      p_CLIN_TYPE         IN POP_CLIN.CLIN_TYPE%TYPE DEFAULT NULL,
      p_CLIN_SUB_CLIN     IN POP_CLIN.CLIN_SUB_CLIN%TYPE DEFAULT NULL,
      p_CLIN_TITLE        IN POP_CLIN.CLIN_TITLE%TYPE DEFAULT NULL,
      p_CLIN_HOURS        IN POP_CLIN.CLIN_HOURS%TYPE DEFAULT NULL,
      p_CLIN_RATE         IN POP_CLIN.CLIN_RATE%TYPE DEFAULT NULL,
      p_CLIN_AMOUNT       IN POP_CLIN.CLIN_AMOUNT%TYPE DEFAULT NULL,
      p_HOURS_COMMITED    IN POP_CLIN.HOURS_COMMITED%TYPE DEFAULT NULL,
      p_LABOR_CATEGORY_ID IN SUB_CLIN.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      p_HASLABORCATEGORIES        IN POP_CLIN.HASLABORCATEGORIES%TYPE DEFAULT NULL,            
      p_LABOR_RATE_TYPE      IN POP_CLIN.LABOR_RATE_TYPE%TYPE DEFAULT NULL,
      p_RATE_TYPE      IN POP_CLIN.RATE_TYPE%TYPE DEFAULT NULL,            
      p_LAST_MODIFIED_BY  IN POP_CLIN.LAST_MODIFIED_BY%TYPE DEFAULT NULL ,
      p_Labor_Amount         IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,
      p_Travel_Amount        IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,
      p_Material_Amount      IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,
      p_ODC_Amount           IN     Clin_Tmo.Clin_Amount%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2 );
  -- delete_POP_CLINete
  PROCEDURE delete_POP_CLIN(
      p_CLIN_ID IN POP_CLIN.CLIN_ID%TYPE,
      p_PStatus OUT VARCHAR2 );
/*begin CLIN_Labor_Category DMLS  --Sridhar Kommana 04/24/2015*/    
  PROCEDURE insert_CLIN_Labor_Category(
      P_CLIN_ID               IN CLIN_LABOR_CATEGORY.CLIN_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_TITLE  IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_TITLE%TYPE DEFAULT NULL,
      P_STD_LABOR_CATEGORY_ID IN CLIN_LABOR_CATEGORY.STD_LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_HIGH_RATE   IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_HIGH_RATE%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_LOW_RATE   IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_LOW_RATE%TYPE DEFAULT NULL,  
      P_APPROVAL_DATE         IN CLIN_LABOR_CATEGORY.APPROVAL_DATE%TYPE DEFAULT NULL,
      P_COMMENTS              IN CLIN_LABOR_CATEGORY.COMMENTS%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_RATE        IN     CLIN_LABOR_CATEGORY.LABOR_CATEGORY_RATE%TYPE DEFAULT NULL,
      P_LC_RATE_TYPE       IN     CLIN_LABOR_CATEGORY.LC_RATE_TYPE%TYPE DEFAULT NULL,
      P_CONTRACTOR                 IN     CLIN_LABOR_CATEGORY.CONTRACTOR%TYPE DEFAULT NULL,
      P_CONTRACTOR_ID               IN     CLIN_LABOR_CATEGORY.CONTRACTOR_ID%TYPE DEFAULT NULL, 
      P_VENDOR                     IN     CLIN_LABOR_CATEGORY.VENDOR%TYPE DEFAULT NULL,    
      p_LABOR_RATE_TYPE      IN CLIN_LABOR_CATEGORY.LABOR_RATE_TYPE%TYPE DEFAULT NULL,      
      P_CREATED_BY            IN CLIN_LABOR_CATEGORY.CREATED_BY%TYPE DEFAULT NULL,
      P_CREATED_ON            IN CLIN_LABOR_CATEGORY.CREATED_ON%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2);
  PROCEDURE update_CLIN_Labor_Category(
      P_LABOR_CATEGORY_ID     IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_TITLE  IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_TITLE%TYPE DEFAULT NULL,
      P_STD_LABOR_CATEGORY_ID IN CLIN_LABOR_CATEGORY.STD_LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_HIGH_RATE   IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_HIGH_RATE%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_LOW_RATE   IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_LOW_RATE%TYPE DEFAULT NULL,   
      P_APPROVAL_DATE         IN CLIN_LABOR_CATEGORY.APPROVAL_DATE%TYPE DEFAULT NULL,
      P_COMMENTS              IN CLIN_LABOR_CATEGORY.COMMENTS%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_RATE        IN     CLIN_LABOR_CATEGORY.LABOR_CATEGORY_RATE%TYPE DEFAULT NULL,
      P_LC_RATE_TYPE       IN     CLIN_LABOR_CATEGORY.LC_RATE_TYPE%TYPE DEFAULT NULL,
      P_CONTRACTOR                 IN     CLIN_LABOR_CATEGORY.CONTRACTOR%TYPE DEFAULT NULL,
      P_CONTRACTOR_ID               IN     CLIN_LABOR_CATEGORY.CONTRACTOR_ID%TYPE DEFAULT NULL,       
      P_VENDOR                     IN     CLIN_LABOR_CATEGORY.VENDOR%TYPE DEFAULT NULL,          
      p_LABOR_RATE_TYPE      IN CLIN_LABOR_CATEGORY.LABOR_RATE_TYPE%TYPE DEFAULT NULL, 
      P_LAST_MODIFIED_BY      IN CLIN_LABOR_CATEGORY.LAST_MODIFIED_BY%TYPE DEFAULT NULL,
      P_LAST_MODIFIED_ON      IN CLIN_LABOR_CATEGORY.LAST_MODIFIED_ON%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2);  
  PROCEDURE update_LC_Rate(
      P_LABOR_CATEGORY_ID     IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_RATE   IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_RATE%TYPE DEFAULT NULL,
      P_LABOR_CATEGORY_HOURS   IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_HOURS%TYPE DEFAULT NULL,   
      P_LAST_MODIFIED_BY      IN CLIN_LABOR_CATEGORY.LAST_MODIFIED_BY%TYPE DEFAULT NULL,
      P_LAST_MODIFIED_ON      IN CLIN_LABOR_CATEGORY.LAST_MODIFIED_ON%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2);        
  PROCEDURE delete_CLIN_Labor_Category( 
      P_LABOR_CATEGORY_ID     IN CLIN_LABOR_CATEGORY.LABOR_CATEGORY_ID%TYPE DEFAULT NULL,
       p_LAST_MODIFIED_BY IN CLIN_LABOR_CATEGORY.LAST_MODIFIED_BY%TYPE DEFAULT NULL,
      p_PStatus OUT VARCHAR2);   
 PROCEDURE SP_GET_CLIN(
    p_UserId                   VARCHAR2 DEFAULT NULL,
    P_CONTRACT_NUMBER          VARCHAR2 DEFAULT NULL,
    P_POP_TYPE                 VARCHAR2 DEFAULT NULL,
    P_CLIN_ID                  NUMBER DEFAULT 0,
    P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL,
    REC_CURSOR OUT SYS_REFCURSOR); 
    
 PROCEDURE sp_get_LaborCategories (
            p_UserId      VARCHAR2,        
            p_PGMName     VARCHAR2,  
            LaborCategories_cursor   OUT SYS_REFCURSOR );
            
PROCEDURE       sp_get_CLIN_LABOR_CATEGORY(   
    p_WORK_ORDERS_ID VARCHAR2 DEFAULT NULL,
    p_LABOR_CATEGORY_ID VARCHAR2 DEFAULT 0,
    p_CLIN_ID VARCHAR2 DEFAULT NULL,
    p_USER VARCHAR2 DEFAULT NULL,
    REC_CURSOR OUT SYS_REFCURSOR);
PROCEDURE sp_get_CLIN_LC_TITLE(
    p_user  VARCHAR2 DEFAULT NULL,
    p_CLIN_ID VARCHAR2 DEFAULT NULL,
    LC_TITLE_cursor OUT SYS_REFCURSOR);    
PROCEDURE sp_get_CLIN_LC_Breakouts (p_USER           VARCHAR2,
                                    p_CLIN_ID        VARCHAR2 DEFAULT NULL ,
                                    LC_REC_CURSOR   OUT SYS_REFCURSOR,
                                    TMO_REC_CURSOR   OUT SYS_REFCURSOR); 
 
 -- Get CLIN BREAKOUT AMOUNTS from CLIN_TMO Table. like Travel, Material and ODC Amounts for the Clin_ID                                   
   PROCEDURE SP_GET_CLIN_BREAKOUT_AMOUNTS(
              p_USER  VARCHAR2  ,
              p_CLIN_ID VARCHAR2  ,
              P_CLIN_TYPE VARCHAR2 DEFAULT NULL,
              TMO_AMOUNTS_CURSOR OUT SYS_REFCURSOR);

END PKG_POP_CLIN;
/