CREATE OR REPLACE PROCEDURE eemrt.SP_GET_SUB_CLIN(
    p_UserId     varchar2 DEFAULT NULL ,
    P_CLIN_ID     NUMBER DEFAULT 0 ,
    P_SUB_CLIN_ID NUMBER DEFAULT 0 ,
    REC_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
  SP_INSERT_AUDIT(p_UserId, 'SUB_CLIN_ID Get SUB Clin details for CLIN_ID= '||P_CLIN_ID||' P_SUB_CLIN_ID='||P_SUB_CLIN_ID);
  --SP_INSERT_AUDIT(p_UserId, 'SP_GET_SUB_CLIN  CLIN_ID= '||P_CLIN_ID||' P_SUB_CLIN_ID='||P_SUB_CLIN_ID);
  OPEN REC_CURSOR FOR SELECT SUB_CLIN_ID, CLIN_ID, SUB_CLIN_NUMBER, SUB_CLIN_TITLE , 
  SUB_CLIN_TYPE , SUB_CLIN_HOURS , SUB_CLIN_RATE , LABOR_RATE_TYPE as SC_LABOR_RATE_TYPE ,
  SUB_CLIN_AMOUNT, LABOR_CATEGORY_ID, L.CATEGORY_NAME AS Standard_LABOR_CATEGORY
  FROM SUB_CLIN
  LEFT OUTER JOIN LABOR_CATEGORIES L ON L.CATEGORY_ID   = LABOR_CATEGORY_ID
  WHERE (CLIN_ID = P_CLIN_ID OR P_CLIN_ID= 0) AND  (SUB_CLIN_ID = P_SUB_CLIN_ID OR P_SUB_CLIN_ID= 0) ORDER BY 1;
EXCEPTION
WHEN OTHERS THEN
  OPEN REC_CURSOR FOR SELECT 1 FROM SUB_CLIN ;
END SP_GET_SUB_CLIN;
/