CREATE OR REPLACE PROCEDURE eemrt.sp_get_FILE_TYPES(
P_FILE_TYPE_ID IN Number,
    file_type_cursor OUT SYS_REFCURSOR)
    
IS
BEGIN
  OPEN file_type_cursor FOR 
  SELECT FILE_TYPE_ID,  DESCRIPTION as FILE_TYPE   FROM FILE_TYPE_LKUP WHERE (FILE_TYPE_ID = p_FILE_TYPE_ID OR p_FILE_TYPE_ID IS NULL);

EXCEPTION
WHEN OTHERS THEN
   OPEN file_type_cursor FOR  SELECT 0 FILE_TYPE_ID, 'None' FILE_TYPE FROM FILE_TYPE_LKUP;
END sp_get_FILE_TYPES;
/