CREATE OR REPLACE PROCEDURE eemrt.SP_GET_CLINS_List(
    P_PERIOD_OF_PERFORMANCE_ID NUMBER DEFAULT NULL ,
    P_CLIN_ID                  NUMBER DEFAULT NULL ,
    P_WOC_ID                   NUMBER DEFAULT 0 ,
    p_WORK_ORDERS_ID           NUMBER DEFAULT 0 ,
    p_UserId                   VARCHAR2 DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR)
AS
  /*
  Procedure : SP_GET_CLINS_List
  Author: Sridhar Kommana
  Date Created : 06/26/2015
  Purpose:  Get Clin list info for a Contract POP
  Update history:
  */
BEGIN
  SP_INSERT_AUDIT(p_UserId, 'SP_GET_CLINS_List: Get work order details P_CLIN_ID='||P_CLIN_ID|| ' P_PERIOD_OF_PERFORMANCE_ID='||P_PERIOD_OF_PERFORMANCE_ID|| ' p_WORK_ORDERS_ID='||p_WORK_ORDERS_ID|| ' P_WOC_ID='||P_WOC_ID);
  OPEN REC_CURSOR FOR
  SELECT DISTINCT   DECODE(CLIN_SUB_CLIN, 'Y', CLIN_ID
    || ':'
    || sub_clin_id,CLIN_ID ) AS SUB_CLIN_ID_DISP, CLIN_ID, sub_clin_id, NVL(SUB_CLIN_NUMBER, CLIN_NUMBER) CLIN_NUMBER_DISP , SUB_CLIN_NUMBER, CLIN_NUMBER, 

    DECODE(CLIN_SUB_CLIN, 'Y', CLIN_NUMBER
    ||'-'
    ||SUB_CLIN_NUMBER,CLIN_NUMBER ) AS SUB_CLIN_NUMBER_DISP, CLIN_SUB_CLIN , CLIN_TITLE , SUB_CLIN_TITLE, NVL(SUB_CLIN_TITLE,CLIN_TITLE) CLIN_TITLE_DISP
  FROM
    (SELECT C.CLIN_ID,
      SC.sub_clin_id,
      CLIN_NUMBER,
      SUB_CLIN_NUMBER,
      NVL(SC.SUB_CLIN_TYPE ,C.CLIN_TYPE) CLIN_TYPE_DISP ,
      C.CLIN_SUB_CLIN ,
      C.CLIN_TITLE ,
      SC.SUB_CLIN_TITLE
    FROM POP_CLIN C
    LEFT OUTER JOIN SUB_CLIN SC
    ON (SC.CLIN_ID = C.CLIN_ID)
    INNER JOIN PERIOD_OF_PERFORMANCE POP
    ON C.PERIOD_OF_PERFORMANCE_ID   = POP.PERIOD_OF_PERFORMANCE_ID
    AND (C.PERIOD_OF_PERFORMANCE_ID = P_PERIOD_OF_PERFORMANCE_ID)
    UNION
    SELECT 0        AS CLIN_ID,
      0             AS sub_clin_id,
      'Select Clin' AS CLIN_NUMBER,
      'Select Clin' AS SUB_CLIN_NUMBER ,
      '0'           AS CLIN_TYPE_DISP ,
      '0'           AS CLIN_SUB_CLIN ,
      '0'           AS CLIN_TITLE ,
      '0'           AS SUB_CLIN_TITLE
    FROM DUAL
    ) TBLCLINS
  ORDER BY 1 ;
EXCEPTION
WHEN OTHERS THEN
  OPEN REC_CURSOR FOR SELECT 0
AS
  CLIN_ID, 0
AS
  sub_clin_id, 'Select Clin'
AS
  CLIN_NUMBER, 'Select Clin'
AS
  SUB_CLIN_NUMBER , '0'
AS
  CLIN_TYPE_DISP , '0'
AS
  CLIN_SUB_CLIN , '0'
AS
  CLIN_TITLE , '0'
AS
  SUB_CLIN_TITLE FROM DUAL;
END SP_GET_CLINS_List;
/