CREATE OR REPLACE PROCEDURE eemrt.SP_GET_SUB_CONTRACTOR(
    p_UserId     varchar2 DEFAULT NULL ,
    p_SUB_CONTRACTOR_ID     NUMBER DEFAULT 0 ,
    p_VENDOR_NAME  varchar2 DEFAULT NULL ,
    p_CONTRACT_NUMBER  varchar2 DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN

  SP_INSERT_AUDIT(p_UserId, 'SP_GET_SUB_CONTRACTOR  P_SUB_CONTRACTOR_ID= '||P_SUB_CONTRACTOR_ID||' P_SUB_CONTRACTOR_ID='||P_SUB_CONTRACTOR_ID);
  OPEN REC_CURSOR FOR SELECT SUB_CONTRACTOR_ID, VENDOR_NAME, CONTRACT_NUMBER , POC_FNAME , POC_FNAME, POC_FNAME , SMALL_BUSINESS
  FROM SUB_CONTRACTOR  
  WHERE (SUB_CONTRACTOR_ID = p_SUB_CONTRACTOR_ID OR p_SUB_CONTRACTOR_ID= 0) 
  AND  (VENDOR_NAME = p_VENDOR_NAME OR p_VENDOR_NAME IS NULL) 
  AND  (CONTRACT_NUMBER = p_CONTRACT_NUMBER OR p_CONTRACT_NUMBER IS NULL) 
  ORDER BY 1;
EXCEPTION
WHEN OTHERS THEN
  OPEN REC_CURSOR FOR SELECT 1 FROM SUB_CONTRACTOR ;
END SP_GET_SUB_CONTRACTOR;
/