CREATE OR REPLACE PROCEDURE eemrt.SP_GET_USER_ACCESS_LIST
(
  P_USERID IN USERS.USERNAME%TYPE,
  REC_CURSOR OUT SYS_REFCURSOR
) AS 
BEGIN
  
  /*
    Created By: Sai Allu
    Created On: 07/13/2016
    Purpose   : Gets all user access rights by given user name.
    
  */
  SP_INSERT_AUDIT( P_USERID,'PKG_USER.SP_GET_USER_ACCESS_LIST');
  OPEN REC_CURSOR FOR
  SELECT
    U.USERNAME,
    UPPER(UR.ROLE) ROLE,
    UF.ID AS "FUNCTIONID",
    UF.TOKEN, 
    UP.ID PermissionId,
    UP.NAME PermissionName
  FROM 
    USERS U JOIN 
    USER_USERROLE_ACCESS UURA ON UPPER(UURA.USERNAME) = UPPER(U.USERNAME) JOIN
    USERROLE UR ON UPPER(U.USERNAME) = UPPER(UR.USERNAME) JOIN
    USERROLE_ACCESS URA ON upper(URA.ROLENAME) = UPPER(UR.ROLE) JOIN
    USER_FUNCTION UF ON UF.ID = URA.USERFUNCTIONID JOIN
    USERPERMISSIONS UP ON UP.ID = URA.USERPERMISSIONID    
  WHERE UPPER(U.USERNAME) = UPPER(P_USERID);

END SP_GET_USER_ACCESS_LIST;
/