CREATE OR REPLACE PROCEDURE eemrt.SP_GET_SMALL_BUSINESS_LIST 
(
  P_USERID IN USERS.USERNAME%TYPE,
  REC_CURSOR OUT SYS_REFCURSOR
) AS 
BEGIN

  /*
    Created By: SAI ALLU
    Created On: 06/28/2016
    Purpose: Gets small business types
  */
  
   SP_INSERT_AUDIT(p_UserId, 'SP_GET_SMALL_BUSINESS_LIST Get all small business types');
   
   OPEN REC_CURSOR FOR 
   SELECT
    CODE,
    DESCRIPTION
  FROM SMALL_BUSINESS_LKUP 
  ORDER BY DESCRIPTION;
  
END SP_GET_SMALL_BUSINESS_LIST;
/