CREATE OR REPLACE PROCEDURE eemrt.sp_get_CLIN_LABOR_CATEGORY(   
    p_WORK_ORDERS_ID VARCHAR2 DEFAULT NULL,
    p_LABOR_CATEGORY_ID VARCHAR2 DEFAULT 0,
    p_CLIN_ID VARCHAR2 DEFAULT NULL,
    p_USER VARCHAR2 DEFAULT NULL,
    REC_CURSOR OUT SYS_REFCURSOR)
AS
  /*
  Procedure : sp_get_CLIN_LABOR_CATEGORY
  Author: Sridhar Kommana
  Date Created : 04/24/2015
  Purpose:  Get clin labor category information.
  Update history:
  sridhar kommana :LABOR_RATE_TYPE
  1) 04/24/2015 : Added p_USER fro auditing/debugging
  2) 05/27/2015 : Added LABOR_CATEGORY_RATE
  3) 05/28/2015 : Added LC_RATE_TYPE  , APPROVAL_DATE,  COMMENTS, CONTRACTOR, VENDOR,
  4) 06/01/2015 : Added p_LABOR_CATEGORY_ID  
  5) 06/04/2015 : Added p_WORK_ORDERS_ID  not using for now
  6) 06/08/2015 : added C.LABOR_RATE_TYPE as  LC_LABOR_RATE_TYPE,
  */
BEGIN
 SP_INSERT_AUDIT( p_USER,'sp_get_CLIN_LABOR_CATEGORY for p_CLIN_ID, p_LABOR_CATEGORY_ID '||p_CLIN_ID ||','||p_LABOR_CATEGORY_ID);   
  OPEN REC_CURSOR FOR 
  SELECT  0 AS WO_LABOR_CATEGORY_ID,
  C.LABOR_CATEGORY_ID, C.CLIN_ID, C.LABOR_CATEGORY_TITLE, 
  C.STD_LABOR_CATEGORY_ID, C.LABOR_CATEGORY_HIGH_RATE, C.LABOR_CATEGORY_LOW_RATE, C.APPROVAL_DATE , C.COMMENTS, L.CATEGORY_NAME AS
  Standard_LABOR_CATEGORY ,  PC.LABOR_RATE_TYPE, C.LABOR_RATE_TYPE as  LC_LABOR_RATE_TYPE, RATE_TYPE, C.LABOR_CATEGORY_RATE, 0 as LABOR_CATEGORY_HOURS,
        0 as  LC_Amount,
        0 as TOT_LABOR_CATEGORY_HOURS,
        0  TOT_LC_Amount,  
   LC_RATE_TYPE, C.CONTRACTOR, C.CONTRACTOR_ID, C.VENDOR
  FROM CLIN_LABOR_CATEGORY C   
  LEFT OUTER JOIN LABOR_CATEGORIES L ON L.CATEGORY_ID = C.STD_LABOR_CATEGORY_ID 
  --LEFT OUTER JOIN WO_LABOR_CATEGORY WOL ON WOL.CLIN_ID = C.CLIN_ID
  INNER JOIN POP_CLIN PC ON PC.CLIN_ID = C.CLIN_ID
  WHERE C.CLIN_ID  = p_CLIN_ID
    AND ( C.LABOR_CATEGORY_ID  = p_LABOR_CATEGORY_ID OR p_LABOR_CATEGORY_ID = 0)
  order by 1 ;
EXCEPTION
WHEN OTHERS THEN
  OPEN REC_CURSOR FOR SELECT 1 AS WO_LABOR_CATEGORY_ID, 1 AS   LABOR_CATEGORY_ID, 1 AS   CLIN_ID, 1 AS   LABOR_CATEGORY_TITLE, 1 AS   STD_LABOR_CATEGORY_ID,
  1 as LABOR_CATEGORY_HIGH_RATE, 1 as LABOR_CATEGORY_LOW_RATE, 1 AS   APPROVAL_DATE , 1 AS   COMMENTS, 1 AS   Standard_LABOR_CATEGORY
  , 1 as  LABOR_RATE_TYPE, 1 as LC_LABOR_RATE_TYPE, 1 as RATE_TYPE, 1 as LABOR_CATEGORY_RATE, 1 as LABOR_CATEGORY_HOURS ,         1 as  LC_Amount,
        1 as TOT_LABOR_CATEGORY_HOURS,
       1  TOT_LC_Amount,   1 as  LC_RATE_TYPE, 1 as CONTRACTOR, 1 as CONTRACTOR_ID,  1 as    VENDOR
  FROM CLIN_LABOR_CATEGORY ;
END sp_get_CLIN_LABOR_CATEGORY;
/