CREATE OR REPLACE PROCEDURE eemrt.sp_get_LSD_WO_FUNDS(
    p_contract_number  varchar2 DEFAULT NULL,
    REC_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
 SP_INSERT_AUDIT('p_UserId', 'sp_get_LSD_WO_FUNDS   '||p_Contract_NUMBER   );
     OPEN REC_CURSOR
      FOR
        SELECT 
              LWF.LSD_WO_ID, LWF.CONTRACT_NUMBER, LWF.LSD, LWF.WORK_ORDERS_ID, LWF.AMOUNT, WO.WORK_ORDER_NUMBER, 
              DC.ACCOUNTING_CODE, DC.QUANTITY_ORDERED, DC.QUANTITY_CANCELLED, DC.QUANTITY_RECEIVED, DC.QUANTITY_BILLED, DC.OBLIGATED_BALANCE, DC.BALANCE_AMOUNT
              FROM LSD_WO_FUNDS LWF
              INNER JOIN DELPHI_CONTRACT_DETAIL DC ON DC.CONTRACT_NUMBER = LWF.CONTRACT_NUMBER
                    AND LWF.LSD = DC.LSD
              INNER JOIN WORK_ORDERS WO ON WO.WORK_ORDERS_ID = LWF.WORK_ORDERS_ID
        Where  (LWF.contract_number = p_contract_number)
        order by LSD;  
EXCEPTION
WHEN OTHERS THEN
  OPEN REC_CURSOR FOR 
        SELECT 1 as LSD_WO_ID, 1 as CONTRACT_NUMBER, 1 as LSD, 1 as WORK_ORDERS_ID, 1 as AMOUNT, 1 as WORK_ORDER_NUMBER, 
        1 as ACCOUNTING_CODE, 1 as QUANTITY_ORDERED, 1 as QUANTITY_CANCELLED, 1 as QUANTITY_RECEIVED, 1 as QUANTITY_BILLED, 1 as OBLIGATED_BALANCE, 1 as BALANCE_AMOUNT
        FROM Dual;
END sp_get_LSD_WO_FUNDS;
/