CREATE OR REPLACE PROCEDURE eemrt.sp_get_CLIN_LC_TITLE(
    p_user  VARCHAR2 DEFAULT NULL,
    p_CLIN_ID VARCHAR2 DEFAULT NULL,
    LC_TITLE_cursor OUT SYS_REFCURSOR)
IS
  /*
  Procedure : sp_get_CLIN_LC_TITLE
  Author: Sridhar Kommana
  Date Created : 07/01/2015
  Purpose:  Get clin labor category Titles.
  Update history:
  */
BEGIN
 SP_INSERT_AUDIT( p_USER,'sp_get_CLIN_LC_TITLE for p_CLIN_ID= '|| p_CLIN_ID);   
  OPEN LC_TITLE_cursor FOR 
 select LABOR_CATEGORY_ID, LABOR_CATEGORY_TITLE  , LABOR_CATEGORY_RATE, LABOR_CATEGORY_HIGH_RATE, LABOR_CATEGORY_LOW_RATE, LC_RATE_TYPE
from CLIN_LABOR_CATEGORY
where clin_id= p_CLIN_ID
ORDER BY 2;  
  
EXCEPTION
WHEN OTHERS THEN
   OPEN LC_TITLE_cursor FOR  SELECT 0 as LABOR_CATEGORY_ID, '' as LABOR_CATEGORY_TITLE , 0 LABOR_CATEGORY_RATE, 0 LABOR_CATEGORY_HIGH_RATE , 0 LABOR_CATEGORY_LOW_RATE, '' LC_RATE_TYPE FROM CLIN_LABOR_CATEGORY;
END sp_get_CLIN_LC_TITLE;
/