CREATE OR REPLACE PROCEDURE eemrt.SP_GET_SUB_CONTRACTOR_CODES
(
  P_USERID IN USERS.USERNAME%TYPE,
  P_SUB_CONTRACTOR_ID IN SUB_CONTRACTOR.SUB_CONTRACTOR_ID%TYPE,
  P_CONTRACTOR_NUMBER IN SUB_CONTRACTOR.CONTRACT_NUMBER%TYPE,
  REC_CURSOR OUT SYS_REFCURSOR
) AS 
BEGIN
  /*
    Created By: SAI ALLU
    Created On: 06/29/2016
    Purpose   : Gets small busines code of given sub contractor id.
  */
  
   SP_INSERT_AUDIT(p_UserId, 'SP_GET_SUB_CONTRACTOR_SMALL_BUSINESS Get all small business types');
   
   OPEN REC_CURSOR FOR 
   SELECT
    SMALL_BUSINESS
  FROM SUB_CONTRACTOR 
  WHERE SUB_CONTRACTOR_ID = P_SUB_CONTRACTOR_ID AND UPPER(CONTRACT_NUMBER) = UPPER(P_CONTRACTOR_NUMBER)
  ORDER BY VENDOR_NAME;
  
END SP_GET_SUB_CONTRACTOR_CODES;
/