CREATE OR REPLACE PROCEDURE eemrt.SP_SUB_GET_CLIN(
   P_CLIN_ID NUMBER DEFAULT NULL ,
   P_SUB_CLIN_ID NUMBER DEFAULT NULL ,
    REC_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
SP_INSERT_AUDIT('p_UserId', 'SP_SUB_GET_CLIN  P_CLIN_ID '||P_CLIN_ID ||' P_SUB_CLIN_ID=' ||P_SUB_CLIN_ID);
     OPEN REC_CURSOR FOR 
      SELECT  SUB_CLIN_ID, CLIN_ID,  SUB_CLIN_NUMBER, SUB_CLIN_TITLE	--, STANDARD_LABOR_CATEGORY	,
      SUB_CLIN_HOURS	,  SUB_CLIN_RATE	,  SUB_CLIN_AMOUNT, Labor_Category_id
      FROM SUB_CLIN
      WHERE (CLIN_ID = P_CLIN_ID OR P_CLIN_ID= NULL)
      AND (SUB_CLIN_ID = P_SUB_CLIN_ID OR SUB_CLIN_ID= NULL)
      ORDER BY 1;
      
      
EXCEPTION WHEN OTHERS
THEN 
      OPEN REC_CURSOR FOR 
      SELECT 1  
       FROM SUB_CLIN ;
End        SP_SUB_GET_CLIN;
/