CREATE OR REPLACE PROCEDURE eemrt.SP_UPDATE_SUBCONTRACTOR_CODES 
(
    P_SUBCONTRACTORID IN SUB_CONTRACTOR.SUB_CONTRACTOR_ID%TYPE
  , P_SMALL_BUSINESS_CODES IN SUB_CONTRACTOR.SMALL_BUSINESS%TYPE
  , P_CONTRACT_NUMBER IN SUB_CONTRACTOR.CONTRACT_NUMBER%TYPE
  , P_USERID IN SUB_CONTRACTOR.CREATED_BY%TYPE 
  , P_PSTATUS OUT VARCHAR2 
) AS 
BEGIN
  
  /*
    Author: Sai Allu
    Date Created : 07/05/2016
    Purpose:  Updates small business codes of a sub contractor
  */      
  
  SP_INSERT_AUDIT(p_UserId, 'PKG_SUB_CONTRACTOR.SP_UPDATE_SUBCONTRACTOR_CODES update of small business codes SUBCONTRACTORID= '||P_SUBCONTRACTORID);
  
  UPDATE SUB_CONTRACTOR SET 
    SMALL_BUSINESS = P_SMALL_BUSINESS_CODES,
    LAST_MODIFIED_BY = P_USERID,
    LAST_MODIFIED_ON = SYSDATE
  WHERE 
    SUB_CONTRACTOR_ID = P_SUBCONTRACTORID AND CONTRACT_NUMBER = P_CONTRACT_NUMBER;
    
  IF SQL%FOUND THEN
    BEGIN
      P_PSTATUS := 'SUCCESS';
      RETURN;
    END;
  END IF;

  EXCEPTION WHEN OTHERS THEN
  BEGIN
    P_PSTATUS := SQLERRM;
    RETURN;
  END;
  
END SP_UPDATE_SUBCONTRACTOR_CODES;
/