CREATE OR REPLACE TRIGGER eemrt.PROGRAM_LOCATIONS_TRG
BEFORE INSERT
ON eemrt.PROGRAM_LOCATIONS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column PGL_ID
  :new.PGL_ID := PROGRAM_LOCATIONS_SEQ.nextval;
END PROGRAM_LOCATIONS_TRG;
/